import type { Metadata } from "next";
import {Inter, Roboto_Mono} from "next/font/google";
import "./globals.css";
import {NavBar} from "@/app/components/NavBar";

const interSans = Inter({
    variable: "--font-inter-sans",
    subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
    variable: "--font-roboto-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} ${robotoMono.variable} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
